// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:wasi@0.1.0

package wasi_cli_0_2_8_exit

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

//go:wasmimport wasi:cli/exit@0.2.8 exit
func wasm_import_exit(arg0 int32)

func Exit(status witTypes.Result[witTypes.Unit, witTypes.Unit]) {

	var option int32
	switch status.Tag() {
	case witTypes.ResultOk:

		option = int32(0)
	case witTypes.ResultErr:

		option = int32(1)
	default:
		panic("unreachable")
	}
	wasm_import_exit(option)

}
