// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:wasi@0.1.0

package wasi_sockets_0_2_8_instance_network

import (
	"go.bytecodealliance.org/wasi/imports/wasi_sockets_0_2_8_network"
)

type Network = wasi_sockets_0_2_8_network.Network

//go:wasmimport wasi:sockets/instance-network@0.2.8 instance-network
func wasm_import_instance_network() int32

func InstanceNetwork() *wasi_sockets_0_2_8_network.Network {

	result := wasm_import_instance_network()
	return wasi_sockets_0_2_8_network.NetworkFromOwnHandle(int32(uintptr(result)))

}
