#!/bin/bash
set -euo pipefail

# Regenerates the committed wit-bindgen bindings for this library.
#
# Uses the wit-bindgen binary from PATH by default; override with e.g.
#   WIT_BINDGEN=~/source/bytecodealliance/wit-bindgen/target/debug/wit-bindgen ./regenerate_bindings.sh
WIT_BINDGEN="${WIT_BINDGEN:-wit-bindgen}"

MODULE=go.bytecodealliance.org/wasi

WORLDS=(
  "bytecodealliance:wasi/wasip2@0.1.0"
  "bytecodealliance:wasi/wasip3@0.1.0"
)

# Remove any previously-generated import bindings.
rm -rf imports tmp
mkdir -p imports

# `wit-bindgen go` generates bindings for a single world at a time, so generate
# each supported world separately. The imports of all worlds are merged into the
# shared imports/ directory, while the exports are kept per world.
for world in "${WORLDS[@]}"; do
  dir=exports/$(echo "$world" | sed 's+[:/@.-]+_+g')
  out="tmp/$world"

  "$WIT_BINDGEN" go \
    -w "$world" \
    --pkg-name "$MODULE" \
    --include-versions \
    --format \
    --quiet \
    --out-dir "$out" \
    wit >/dev/null

  # Merge this world's imports into the shared imports. Packages generated by
  # more than one world must be identical.
  for pkg in "$out"/imports/*; do
    name=$(basename "$pkg")
    if [ -e "imports/$name" ]; then
      if ! diff -r "imports/$name" "$pkg" >/dev/null; then
        echo "error: imports/$name differs between worlds" >&2
        exit 1
      fi
    else
      cp -r "$pkg" imports/
    fi
  done

  # Keep only the generated export glue; the export_* trampolines next to it
  # are hand-written. Point the glue at the per-world trampoline packages.
  rm -rf "$dir/wit_exports"
  mkdir -p "$dir"
  cp -r "$out/exports/wit_exports" "$dir/"
  sed -i "s+\"$MODULE/exports/export_+\"$MODULE/$dir/export_+g" "$dir/wit_exports/wit_exports.go"

  # Allow the package to compile on non-wasm hosts despite bodyless
  # //go:wasmimport declarations (same trick as the generated imports).
  if [ ! -f "$dir/wit_exports/empty.s" ]; then
    cat > "$dir/wit_exports/empty.s" <<'EOF'
// This file exists for testing this package without WebAssembly,
// allowing empty function bodies with a //go:wasmimport directive.
// See https://pkg.go.dev/cmd/compile for more information.
EOF
  fi
done

rm -rf tmp

go mod tidy
