// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:wasi@0.1.0

package wit_exports

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"go.bytecodealliance.org/wasi/exports/bytecodealliance_wasi_wasip2_0_1_0/export_wasi_http_0_2_8_incoming_handler"
	"go.bytecodealliance.org/wasi/imports/wasi_http_0_2_8_types"
	"runtime"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport wasi:http/incoming-handler@0.2.8#handle
func wasm_export_wasi_http_0_2_8_incoming_handler_handle(arg0 int32, arg1 int32) {

	export_wasi_http_0_2_8_incoming_handler.Handle(wasi_http_0_2_8_types.IncomingRequestFromOwnHandle(int32(uintptr(arg0))), wasi_http_0_2_8_types.ResponseOutparamFromOwnHandle(int32(uintptr(arg1))))

}
