// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:wasi@0.1.0

package wasi_cli_0_2_8_stdin

import (
	"go.bytecodealliance.org/wasi/imports/wasi_io_0_2_8_streams"
)

type InputStream = wasi_io_0_2_8_streams.InputStream

//go:wasmimport wasi:cli/stdin@0.2.8 get-stdin
func wasm_import_get_stdin() int32

func GetStdin() *wasi_io_0_2_8_streams.InputStream {

	result := wasm_import_get_stdin()
	return wasi_io_0_2_8_streams.InputStreamFromOwnHandle(int32(uintptr(result)))

}
