// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:wasi@0.1.0

package wasi_logging_0_1_0_draft_logging

import (
	"runtime"
	"unsafe"
)

const (
	// Describes messages about the values of variables and the flow of
	// control within a program.
	Level_Trace uint8 = 0
	// Describes messages likely to be of interest to someone debugging a
	// program.
	Level_Debug uint8 = 1
	// Describes messages likely to be of interest to someone monitoring a
	// program.
	Level_Info uint8 = 2
	// Describes messages indicating hazardous situations.
	Level_Warn uint8 = 3
	// Describes messages indicating serious errors.
	Level_Error uint8 = 4
	// Describes messages indicating fatal errors.
	Level_Critical uint8 = 5
)

// A log level, describing a kind of message.
type Level = uint8

//go:wasmimport wasi:logging/logging@0.1.0-draft log
func wasm_import_log(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32)

func Log(level Level, context string, message string) {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(context))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(message))
	pinner.Pin(utf80)
	wasm_import_log(int32(level), uintptr(utf8), uint32(len(context)), uintptr(utf80), uint32(len(message)))

}
